"""create initial analytics schema

Revision ID: 9a999e64b310
Revises:
Create Date: 2026-09-23 21:11:32.579865

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a999e64b310"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'suspended')", name="ck_customers_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_customers_created_at", "customers", ["created_at"], unique=False)
    op.create_index("ix_customers_status", "customers", ["status"], unique=False)
    op.create_table(
        "seed_runs",
        sa.Column("seed_name", sa.String(length=100), nullable=False),
        sa.Column("seeded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("seed_name"),
    )
    op.create_table(
        "drivers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("license_number", sa.String(length=50), nullable=False),
        sa.Column("license_expiry", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'suspended')", name="ck_drivers_status"
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("license_number"),
    )
    op.create_index("ix_drivers_customer_id", "drivers", ["customer_id"], unique=False)
    op.create_index("ix_drivers_license_expiry", "drivers", ["license_expiry"], unique=False)
    op.create_index("ix_drivers_status", "drivers", ["status"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('paid', 'pending', 'overdue', 'cancelled')", name="ck_invoices_status"
        ),
        sa.CheckConstraint("amount >= 0", name="ck_invoices_amount_nonnegative"),
        sa.CheckConstraint("tax_amount >= 0", name="ck_invoices_tax_nonnegative"),
        sa.CheckConstraint("total_amount >= amount", name="ck_invoices_total_covers_amount"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_invoices_customer_date", "invoices", ["customer_id", "invoice_date"], unique=False
    )
    op.create_index("ix_invoices_customer_id", "invoices", ["customer_id"], unique=False)
    op.create_index("ix_invoices_invoice_date", "invoices", ["invoice_date"], unique=False)
    op.create_index("ix_invoices_status", "invoices", ["status"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("plan_name", sa.String(length=50), nullable=False),
        sa.Column("monthly_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'cancelled', 'expired')", name="ck_subscriptions_status"
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date", name="ck_subscriptions_date_order"
        ),
        sa.CheckConstraint("monthly_price >= 0", name="ck_subscriptions_price_nonnegative"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_subscriptions_customer_id", "subscriptions", ["customer_id"], unique=False)
    op.create_index("ix_subscriptions_start_date", "subscriptions", ["start_date"], unique=False)
    op.create_index("ix_subscriptions_status", "subscriptions", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint("status IN ('active', 'inactive', 'invited')", name="ck_users_status"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_customer_id", "users", ["customer_id"], unique=False)
    op.create_index("ix_users_status", "users", ["status"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("registration_number", sa.String(length=30), nullable=False),
        sa.Column("vehicle_type", sa.String(length=50), nullable=False),
        sa.Column("manufacturer", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("fuel_type", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "fuel_type IN ('diesel', 'petrol', 'cng', 'electric')", name="ck_vehicles_fuel_type"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'maintenance', 'retired')", name="ck_vehicles_status"
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("registration_number"),
    )
    op.create_index("ix_vehicles_customer_id", "vehicles", ["customer_id"], unique=False)
    op.create_index(
        "ix_vehicles_customer_status", "vehicles", ["customer_id", "status"], unique=False
    )
    op.create_index("ix_vehicles_status", "vehicles", ["status"], unique=False)
    op.create_table(
        "fuel_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("fuel_date", sa.Date(), nullable=False),
        sa.Column("liters", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("price_per_liter", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.CheckConstraint("liters > 0", name="ck_fuel_liters_positive"),
        sa.CheckConstraint("price_per_liter >= 0", name="ck_fuel_price_nonnegative"),
        sa.CheckConstraint("total_cost >= 0", name="ck_fuel_total_nonnegative"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fuel_records_customer_date", "fuel_records", ["customer_id", "fuel_date"], unique=False
    )
    op.create_index("ix_fuel_records_customer_id", "fuel_records", ["customer_id"], unique=False)
    op.create_index("ix_fuel_records_fuel_date", "fuel_records", ["fuel_date"], unique=False)
    op.create_index("ix_fuel_records_vehicle_id", "fuel_records", ["vehicle_id"], unique=False)
    op.create_table(
        "maintenance_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("maintenance_date", sa.Date(), nullable=False),
        sa.Column("maintenance_type", sa.String(length=100), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('scheduled', 'completed', 'cancelled')", name="ck_maintenance_status"
        ),
        sa.CheckConstraint("cost >= 0", name="ck_maintenance_cost_nonnegative"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_maintenance_records_customer_id", "maintenance_records", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_maintenance_records_date", "maintenance_records", ["maintenance_date"], unique=False
    )
    op.create_index(
        "ix_maintenance_records_status", "maintenance_records", ["status"], unique=False
    )
    op.create_index(
        "ix_maintenance_records_vehicle_id", "maintenance_records", ["vehicle_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "payment_method IN ('bank_transfer', 'credit_card', 'direct_debit', 'cash')",
            name="ck_payments_method",
        ),
        sa.CheckConstraint("status IN ('paid', 'pending', 'failed')", name="ck_payments_status"),
        sa.CheckConstraint("amount > 0", name="ck_payments_amount_positive"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_payments_customer_date", "payments", ["customer_id", "payment_date"], unique=False
    )
    op.create_index("ix_payments_customer_id", "payments", ["customer_id"], unique=False)
    op.create_index("ix_payments_invoice_id", "payments", ["invoice_id"], unique=False)
    op.create_index("ix_payments_payment_date", "payments", ["payment_date"], unique=False)
    op.create_index("ix_payments_status", "payments", ["status"], unique=False)
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_location", sa.String(length=200), nullable=False),
        sa.Column("end_location", sa.String(length=200), nullable=False),
        sa.Column("distance_km", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("fuel_consumed_liters", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("idle_time_minutes", sa.Integer(), nullable=False),
        sa.Column("trip_status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "trip_status IN ('completed', 'cancelled', 'in_progress')", name="ck_trips_status"
        ),
        sa.CheckConstraint("distance_km >= 0", name="ck_trips_distance_nonnegative"),
        sa.CheckConstraint(
            "end_time IS NULL OR end_time >= start_time", name="ck_trips_time_order"
        ),
        sa.CheckConstraint("fuel_consumed_liters >= 0", name="ck_trips_fuel_nonnegative"),
        sa.CheckConstraint("idle_time_minutes >= 0", name="ck_trips_idle_nonnegative"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_trips_customer_id", "trips", ["customer_id"], unique=False)
    op.create_index(
        "ix_trips_customer_start_time", "trips", ["customer_id", "start_time"], unique=False
    )
    op.create_index("ix_trips_driver_id", "trips", ["driver_id"], unique=False)
    op.create_index("ix_trips_start_time", "trips", ["start_time"], unique=False)
    op.create_index("ix_trips_status", "trips", ["trip_status"], unique=False)
    op.create_index("ix_trips_vehicle_id", "trips", ["vehicle_id"], unique=False)
    op.create_table(
        "vehicle_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("speed_kmph", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name="ck_locations_latitude"),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name="ck_locations_longitude"),
        sa.CheckConstraint("speed_kmph >= 0", name="ck_locations_speed_nonnegative"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vehicle_locations_recorded_at", "vehicle_locations", ["recorded_at"], unique=False
    )
    op.create_index(
        "ix_vehicle_locations_vehicle_id", "vehicle_locations", ["vehicle_id"], unique=False
    )
    op.create_index(
        "ix_vehicle_locations_vehicle_recorded_at",
        "vehicle_locations",
        ["vehicle_id", "recorded_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vehicle_locations_vehicle_recorded_at", table_name="vehicle_locations")
    op.drop_index("ix_vehicle_locations_vehicle_id", table_name="vehicle_locations")
    op.drop_index("ix_vehicle_locations_recorded_at", table_name="vehicle_locations")
    op.drop_table("vehicle_locations")
    op.drop_index("ix_trips_vehicle_id", table_name="trips")
    op.drop_index("ix_trips_status", table_name="trips")
    op.drop_index("ix_trips_start_time", table_name="trips")
    op.drop_index("ix_trips_driver_id", table_name="trips")
    op.drop_index("ix_trips_customer_start_time", table_name="trips")
    op.drop_index("ix_trips_customer_id", table_name="trips")
    op.drop_table("trips")
    op.drop_index("ix_payments_status", table_name="payments")
    op.drop_index("ix_payments_payment_date", table_name="payments")
    op.drop_index("ix_payments_invoice_id", table_name="payments")
    op.drop_index("ix_payments_customer_id", table_name="payments")
    op.drop_index("ix_payments_customer_date", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_maintenance_records_vehicle_id", table_name="maintenance_records")
    op.drop_index("ix_maintenance_records_status", table_name="maintenance_records")
    op.drop_index("ix_maintenance_records_date", table_name="maintenance_records")
    op.drop_index("ix_maintenance_records_customer_id", table_name="maintenance_records")
    op.drop_table("maintenance_records")
    op.drop_index("ix_fuel_records_vehicle_id", table_name="fuel_records")
    op.drop_index("ix_fuel_records_fuel_date", table_name="fuel_records")
    op.drop_index("ix_fuel_records_customer_id", table_name="fuel_records")
    op.drop_index("ix_fuel_records_customer_date", table_name="fuel_records")
    op.drop_table("fuel_records")
    op.drop_index("ix_vehicles_status", table_name="vehicles")
    op.drop_index("ix_vehicles_customer_status", table_name="vehicles")
    op.drop_index("ix_vehicles_customer_id", table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index("ix_users_status", table_name="users")
    op.drop_index("ix_users_customer_id", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_subscriptions_status", table_name="subscriptions")
    op.drop_index("ix_subscriptions_start_date", table_name="subscriptions")
    op.drop_index("ix_subscriptions_customer_id", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("ix_invoices_status", table_name="invoices")
    op.drop_index("ix_invoices_invoice_date", table_name="invoices")
    op.drop_index("ix_invoices_customer_id", table_name="invoices")
    op.drop_index("ix_invoices_customer_date", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index("ix_drivers_status", table_name="drivers")
    op.drop_index("ix_drivers_license_expiry", table_name="drivers")
    op.drop_index("ix_drivers_customer_id", table_name="drivers")
    op.drop_table("drivers")
    op.drop_table("seed_runs")
    op.drop_index("ix_customers_status", table_name="customers")
    op.drop_index("ix_customers_created_at", table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
